Add discovery workflow.

diff --git a/.bitrise/bitrise_adhoc.yml b/.bitrise/bitrise_adhoc.yml
--- a/.bitrise/bitrise_adhoc.yml
+++ b/.bitrise/bitrise_adhoc.yml
@@ -1,5 +1,58 @@
 ---
 format_version: '13'
 workflows:
-  _pr_adhoc_build:
+  _pr_adhoc_build_discovery:
     steps:
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Assuming our commit message is in the correct format, we decide which tests to go on with
+            # $GIT_CLONE_COMMIT_MESSAGE_BODY
+            echo "Git msg: ${GIT_CLONE_COMMIT_MESSAGE_BODY}"
+            echo "Bitrise Pull Request: "
+            echo $BITRISE_PULL_REQUEST
+            echo "Bitrise Git Message: "
+            echo $BITRISE_GIT_MESSAGE
+
+            if [[ ! -z $BITRISE_PULL_REQUEST ]]; then
+              envman add --key PR_NUMBER --value $BITRISE_PULL_REQUEST
+            else
+              envman add --key PR_NUMBER --value "NOT_PR"
+            fi
+            if [[ $BITRISE_GIT_MESSAGE == *"Student"* ]]; then
+              envman add --key REQUIRE_STUDENT --value "true"
+            fi
+
+            if [[ $BITRISE_GIT_MESSAGE == *"Teacher"* ]]; then
+              envman add --key REQUIRE_TEACHER --value "true"
+            fi
+
+            if [[ $BITRISE_GIT_MESSAGE == *"Parent"* ]]; then
+              envman add --key REQUIRE_PARENT --value "true"
+            fi
+
+            if [[ $BITRISE_GIT_MESSAGE == *"Horizon"* ]]; then
+              envman add --key REQUIRE_HORIZON --value "true"
+            fi
+
+            if [[ $BITRISE_GIT_MESSAGE == *"affects: All"* ]]; then
+              envman add --key REQUIRE_PARENT --value "true" &&
+              envman add --key REQUIRE_TEACHER --value "true" &&
+              envman add --key REQUIRE_STUDENT --value "true" &&
+              envman add --key REQUIRE_HORIZON --value
+            fi
+        title: Discover Which Apps To Build
+    summary: |-
+      This step analyzes the pull request's description and decides which apps to build.
+
+      Outputs if conditions are met for each app:
+      - $REQUIRE_PARENT=true
+      - $REQUIRE_TEACHER=true
+      - $REQUIRE_STUDENT=true
+      - $REQUIRE_HORIZON=true
