lint and jest failures as PR comments

diff --git a/scripts/build_automation/bitrise_workflows/tests.yml b/scripts/build_automation/bitrise_workflows/tests.yml
--- a/scripts/build_automation/bitrise_workflows/tests.yml
+++ b/scripts/build_automation/bitrise_workflows/tests.yml
@@ -27,7 +27,6 @@ workflows:
             if printf "%s\n" "$BITRISE_GIT_MESSAGE" | grep -iF "[run nightly]"; then
                 envman add --key RUN_NIGHTLY --value YES
             fi
-
     - build-router-start:
         inputs:
         - access_token: "$BITRISE_CI_TOKEN"
@@ -135,11 +134,13 @@ workflows:
             zip --quiet -r "$BITRISE_DEPLOY_DIR/citests.xcresult.zip" scripts/coverage/citests.xcresult
         is_always_run: true
     - build-router-wait:
+        title: Wait for danger-yarn sub-build to succeed
         inputs:
         - access_token: "$BITRISE_CI_TOKEN"
         - buildslugs: "$DANGER_YARN_SLUG"
     - script:
         title: Get danger-yarn results
+        is_always_run: true
         inputs:
         - runner_bin: "/bin/zsh"
         - content: |-
@@ -148,11 +149,12 @@ workflows:
 
             ARTIFACT_SLUG=$(curl -H "Authorization: $BITRISE_CI_TOKEN" \
                 "https://api.bitrise.io/v0.1/apps/${BITRISE_APP_SLUG}/builds/${DANGER_YARN_SLUG}/artifacts" |
-                jq -r '.data[] | select(.title == "yarn-coverage.tar.xz").slug')
+                jq -r '.data[] | select(.title == "results.tar.xz").slug')
             ARTIFACT_URL=$(curl -H "Authorization: $BITRISE_CI_TOKEN" \
                 "https://api.bitrise.io/v0.1/apps/${BITRISE_APP_SLUG}/builds/${DANGER_YARN_SLUG}/artifacts/${ARTIFACT_SLUG}" |
                 jq -r '.data.expiring_download_url')
             curl -L $ARTIFACT_URL | tar xJf -
+            cat tmp/report_to_danger_subbuild.md >> tmp/report_to_danger.md || true
     - script:
         title: Report Coverage
         run_if: .IsCI
@@ -415,7 +417,7 @@ workflows:
             # fail if any commands fails
             set -eo pipefail
 
-            ./scripts/runSwiftLint.sh 2>&1 | xcbeautify
+            ./scripts/runSwiftLint.sh 2>&1 | xcbeautify | tee tmp/swift-lint-results.txt
     - yarn:
         title: yarn install root dependencies
     - yarn:
@@ -438,12 +440,38 @@ workflows:
         - workdir: "$BITRISE_SOURCE_DIR/rn/Teacher"
         - command: test --silent --coverage --color
     - script:
-        title: Save coverage
+        title: Save results
+        is_always_run: true
         inputs:
         - runner_bin: "/bin/zsh"
         - content: |-
             #!/bin/zsh
             set -euxo pipefail
 
-            tar -cJf $BITRISE_DEPLOY_DIR/yarn-coverage.tar.xz scripts/coverage/react-native
+            function htmlize {
+                sed -e $'s/\x1b\\[[0-9;]*[a-zA-Z]//g; 's/&/&amp;/g; s/</&lt/g; s/>/&gt/g'
+            }
+
+            if [[ -s tmp/swift-lint-results.txt ]]; then
+                echo "<details><summary>:x: Swift lint</summary>"
+                echo "<pre>$(htmlize < tmp/swift-lint-results.txt)</pre>"
+                echo "</details>"
+            fi >> tmp/report_to_danger_subbuild.md
+
+            if [[ -s tmp/yarn-lint-results.txt ]]; then
+                echo "<details><summary>:x: Yarn lint</summary>"
+                echo "<pre>$(htmlize < tmp/yarn-lint-results.txt)</pre>"
+                echo "</details>"
+            fi >> tmp/report_to_danger_subbuild.md
+
+            sed -n '/Summary of all failing tests/,$ p' < tmp/yarn-tests.txt > tmp/yarn-test-failures.txt
+            if [[ -s tmp/yarn-failures.txt ]]; then
+                echo "<details><summary>:x: JS tests</summary>"
+                echo "<pre>$(htmlize < tmp/yarn-failures.txt)</pre>"
+                echo "</details>"
+            fi
+
+            tar -cJf $BITRISE_DEPLOY_DIR/results.tar.xz \
+                scripts/coverage/react-native \
+                tmp/report_to_danger_subbuild.md
     - deploy-to-bitrise-io: {}
