fix timezone issue on bitrise

diff --git a/scripts/build_automation/bitrise_workflows/tests.yml b/scripts/build_automation/bitrise_workflows/tests.yml
--- a/scripts/build_automation/bitrise_workflows/tests.yml
+++ b/scripts/build_automation/bitrise_workflows/tests.yml
@@ -40,6 +40,15 @@ workflows:
             git checkout -
     # - cache-pull: {}
     - script:
+        title: Set TimeZone to MST
+        run_if: .IsCI
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -ex
+            sudo systemsetup -settimezone America/Denver
+    - script:
         title: super-hacky-temp-carthage-cache
         run_if: .IsCI
         inputs:
@@ -218,14 +227,6 @@ workflows:
             # Set all changed files to now
             git checkout -
     - cache-pull: {}
-    - script:
-            inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                # fail if any commands fails
-                set -ex
-                sudo systemsetup -settimezone America/Denver
-            title: Set TimeZone to MST
     - script:
         title: brew tap
         run_if: .IsCI
